spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myappdb
    username: postgres
    password: qwer1234!!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
